rfid/config/routes.rb
Rfid::Application.routes.draw do
  get "reports/students_in"
  get "reports/students_out"
  resources :rfid_logs

  resources :students

end

rfid/app/models/rfid_log.rb
class RfidLog < ActiveRecord::Base

	def self.search(search)
		if search
			# find(:all, :conditions => ["card_rfid LIKE ? OR full_name LIKE ? OR first_name LIKE ?", "%#{search}%","%#{search}%","%#{search}%"] )
			find(:all, :conditions => ["card_rfid LIKE ? OR full_name LIKE ? OR id_number LIKE ? OR classification LIKE ?" ,"%#{ search}%","%#{search}%","%#{search}%","%#{search}%"] )
			
		else
			find(:all)
		end
	end

end

rfid/app/models/student.rb
class Student < ActiveRecord::Base
	def full_name 
		last_name.upcase + ", " + first_name.capitalize + " " + middle_name.capitalize 
    end
    def course_year
    	course.upcase + " " + year_level.to_s
    end
end

rfid/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rfid/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def students_in
  	@students_in  = RfidLog.all
  end

  def students_out
  	@students_out = RfidLog.all
  end
end

rfid/app/controllers/rfid_logs_controller.rb
class RfidLogsController < ApplicationController
  before_action :set_rfid_log, only: [:show, :edit, :update, :destroy]

  # GET /rfid_logs
  # GET /rfid_logs.json
  def index
    # @rfid_logs = RfidLog.all
    @rfid_logs = RfidLog.search(params[:search])
  end

  # GET /rfid_logs/1
  # GET /rfid_logs/1.json
  def show
  end

  # GET /rfid_logs/new
  def new
    @rfid_log = RfidLog.new
  end

  # GET /rfid_logs/1/edit
  def edit
  end

  # POST /rfid_logs
  # POST /rfid_logs.json
  def create
    @rfid_log = RfidLog.new(rfid_log_params)

    respond_to do |format|
      if @rfid_log.save
        format.html { redirect_to @rfid_log, notice: 'Rfid log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rfid_log }
      else
        format.html { render action: 'new' }
        format.json { render json: @rfid_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rfid_logs/1
  # PATCH/PUT /rfid_logs/1.json
  def update
    respond_to do |format|
      if @rfid_log.update(rfid_log_params)
        format.html { redirect_to @rfid_log, notice: 'Rfid log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rfid_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rfid_logs/1
  # DELETE /rfid_logs/1.json
  def destroy
    @rfid_log.destroy
    respond_to do |format|
      format.html { redirect_to rfid_logs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rfid_log
      @rfid_log = RfidLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rfid_log_params
      params.require(:rfid_log).permit(:card_rfid, :time)
    end
end

rfid/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:card_rfid, :id_number, :first_name, :middle_name, :last_name, :course, :year_level, :contact_number, :stype, :entered)
    end
end

rfid/app/helpers/application_helper.rb
module ApplicationHelper
end

rfid/app/helpers/reports_helper.rb
module ReportsHelper
end

rfid/app/helpers/rfid_logs_helper.rb
module RfidLogsHelper
end

rfid/app/helpers/students_helper.rb
module StudentsHelper
end

rfid/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>rfid</title>

	<!-- Bootstrap core CSS -->

	<%= stylesheet_link_tag "custom1", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>  




</head>

<body>       
	<div class="container">
		<%= yield %>
	</div>
</div><!-- /#wrapper -->

<!-- JavaScript -->

</body>
</html>

rfid/app/views/reports/students_in.html.erb
<center>
<h1>Students In</h1>
<%= link_to '| Home |', 'http://0.0.0.0:3000/' %>
<%= link_to '| Logs |','http://0.0.0.0:3001/rfid_logs' %>
<%= link_to '| Records |','http://0.0.0.0:3001/students' %>
<%= link_to '| New record |', new_student_path %>
<%= link_to '| Students In |', 'http://0.0.0.0:3001/reports/students_in' %><br><br>


<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Time-in</th>


		</tr>
	</thead>

	<% s_time = Time.now %>
	<% status = "out"%>
	<% count = 0 %>



	<tbody>
		<% Student.all.each do |student| %>
		<tr>
			<% RfidLog.where(card_rfid: student.card_rfid).each do |my_payment| %>

			<% status = my_payment.in_out  %>
			<% s_time = my_payment.time %>
			<% end %>

			<% if status == "in" %>
			<% count += 1 %>
			<td><%= student.id_number %></td>
			<td><%= student.full_name %></td>
			<!-- <td><%= status  %></td>  -->
			<td><%= s_time.localtime.strftime("%Y-%m-%d %H:%M:%S")  %></td>
			<% end %>


		</tr>
		<% end %>

		</tbody>

<!-- 	<tfoot>
		<tr>
			<td></td>
			<td>Number of Students inside:</td>
			<td><b><%= count %></b></td>


		</tr>
	</tfoot> -->
				<h2>Number of Students inside: <%= count %> </h2>


</table>

<br>

rfid/app/views/reports/students_out.html.erb
<center>
<h1>Students Out</h1>
<%= link_to '| Home |', 'http://0.0.0.0:3000/' %>
<%= link_to '| Logs |','http://0.0.0.0:3001/rfid_logs' %>
<%= link_to '| Records |','http://0.0.0.0:3001/students' %>
<%= link_to '| New record |', new_student_path %>
<%= link_to '| Students In |', 'http://0.0.0.0:3001/reports/students_in' %><br><br>



<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Status</th>


		</tr>
	</thead>

	<% status = "out"%>
	<% count = 0 %>



	<tbody>
		<% Student.all.each do |student| %>
		<tr>
			<% RfidLog.where(card_rfid: student.card_rfid).each do |my_payment| %>

			<% status = my_payment.in_out  %>

			<% end %>

			<% if status == "out" %>
			<% count += 1 %>
			<td><%= student.id_number %></td>
			<td><%= student.full_name %></td>
			<td><%= status %></td>
			<% end %>


		</tr>
		<% end %>

		</tbody>

<!-- 	<tfoot>
		<tr>
			<td></td>
			<td>Number of Students inside:</td>
			<td><b><%= count %></b></td>


		</tr>
	</tfoot> -->
				<h2>Number of Students outside: <%= count %> </h2>


</table>

<br>

rfid/app/views/rfid_logs/_form.html.erb
<%= form_for(@rfid_log) do |f| %>
  <% if @rfid_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rfid_log.errors.count, "error") %> prohibited this rfid_log from being saved:</h2>

      <ul>
      <% @rfid_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_rfid %><br>
    <%= f.text_field :card_rfid %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rfid/app/views/rfid_logs/edit.html.erb
<center>
<h1>Editing Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @rfid_log %> |
<%= link_to 'Back', rfid_logs_path %>

rfid/app/views/rfid_logs/index.html.erb
<center>
<h1>Logs</h1>
<%= link_to '| Home |', 'http://0.0.0.0:3000/' %>
<%= link_to '| Logs |','http://0.0.0.0:3001/rfid_logs' %>
<%= link_to '| Records |','http://0.0.0.0:3001/students' %>
<%= link_to '| New record |', new_student_path %>
<%= link_to '| Students In |', 'http://0.0.0.0:3001/reports/students_in' %><br><br>


<%= form_tag rfid_logs_path, :method => 'get' do %>
<div class="form-group pull-right">
  <%= text_field_tag :search, params[:search], :placeholder=>'Search by Name, ID, Classification' %> 
</div>

<% end %>


<table>
  <thead>
    <tr>
      <!-- <th>Card rfid</th> -->
      <th>ID number</th>
      <th>Full Name</th>
      <th>Classification</th>
      <th>Course/Profession</th>
      <th>In/Out</th>
      <th>Time</th>



      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rfid_logs.each do |rfid_log| %>
    <tr>
      <% s = Student.where(card_rfid: rfid_log.card_rfid).take %>
      <!-- <td><%= rfid_log.card_rfid %></td> -->
      <td><%= rfid_log.id_number %></td>
      <td><%= rfid_log.full_name %></td>
      <td><%= rfid_log.classification %></td>

      <td><%= s.course_year %></td>
      <td><%= rfid_log.in_out.upcase %></td>

      <td><%= rfid_log.time.localtime.strftime("%Y-%m-%d %H:%M:%S") %></td>


      <!-- c = RfidLog.where(card_rfid: rfid).count -->




      <td><%= link_to 'Show', rfid_log %></td>
      <!-- <td><%= link_to 'Edit', edit_rfid_log_path(rfid_log) %></td>
      <td><%= link_to 'Destroy', rfid_log, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- 
<%= link_to 'New Rfid log', new_rfid_log_path %>
 -->

rfid/app/views/rfid_logs/new.html.erb
<center>
<h1>New rfid_log</h1>

<%= render 'form' %>

<%= link_to 'Back', rfid_logs_path %>

rfid/app/views/rfid_logs/show.html.erb
<style type="text/css">
	center {
		padding-top: 100px;
	}
</style>
<center>
<p id="notice"><%= notice %></p>

<p>
  <strong>ID Number:</strong>
  <%= @rfid_log.id_number %>
</p>


<p>
  <strong>Full name:</strong>
  <%= @rfid_log.full_name %>
</p>


<p>
  <strong>Position:</strong>
  <%= @rfid_log.classification %>
</p>

<p>
  <strong>Card rfid:</strong>
  <%= @rfid_log.card_rfid %>
</p>

<p>
  <strong>Time:</strong>
  <%= @rfid_log.time %>
</p>

<!-- <%= link_to 'Edit', edit_rfid_log_path(@rfid_log) %> | -->
<%= link_to 'Back', rfid_logs_path %>

rfid/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
<% if @student.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

  <ul>
    <% @student.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :card_rfid %><br>
  <%= f.text_field :card_rfid %>
</div>
<div class="field">
  <%= f.label :id_number %><br>
  <%= f.text_field :id_number %>
</div>
<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :middle_name %><br>
  <%= f.text_field :middle_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</div>
<div class="field">
  <%= f.label 'classification' %><br>
  <%= f.text_field :stype %>
</div>


<div class="field">
  <%= f.label "Course/Position" %><br>
  <%= f.text_field :course %>
</div>
<div class="field">
  <%= f.label "Year Level(if student)" %><br>
  <%= f.number_field :year_level %>
</div>
<div class="field">
  <%= f.label :contact_number %><br>
  <%= f.text_field :contact_number %>
</div>


<div class="actions">
  <%= f.submit "Submit" %>
</div>
<% end %>

rfid/app/views/students/edit.html.erb
<center>
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

rfid/app/views/students/index.html.erb
<center>


<h1>Listing Records</h1>
<%= link_to '| Home |', 'http://0.0.0.0:3000/' %>
<%= link_to '| Logs |','http://0.0.0.0:3001/rfid_logs' %>
<%= link_to '| Records |','http://0.0.0.0:3001/students' %>
<%= link_to '| New record |', new_student_path %>
<%= link_to '| Students In |', 'http://0.0.0.0:3001/reports/students_in' %><br><br>

<table>
  <thead>
    <tr>
      <th>Card rfid</th>
      <th>Id number</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Course</th>
      <th>Year level</th>
      <th>Contact number</th>
      <th>Type</th>
      <!-- <th>Entered</th> -->

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.card_rfid %></td>
        <td><%= student.id_number %></td>
        <td><%= student.first_name %></td>
        <td><%= student.middle_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.course %></td>
        <td><%= student.year_level %></td>
        <td><%= student.contact_number %></td>
        <td><%= student.stype %></td>
        <!-- <td><%= student.entered %></td> -->

        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

rfid/app/views/students/new.html.erb
<center>
<h1>New Record</h1>
<%= link_to '| Home |', 'http://0.0.0.0:3000/' %>
<%= link_to '| Logs |','http://0.0.0.0:3001/rfid_logs' %>
<%= link_to '| Records |','http://0.0.0.0:3001/students' %>
<%= link_to '| New record |', new_student_path %>
<%= link_to '| Students In |', 'http://0.0.0.0:3001/reports/students_in' %><br><br>

<%= render 'form' %>

<!-- <%= link_to 'Back', students_path %> -->

rfid/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card rfid:</strong>
  <%= @student.card_rfid %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @student.id_number %>
</p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @student.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<p>
  <strong>Year level:</strong>
  <%= @student.year_level %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @student.contact_number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @student.stype %>
</p>

<p>
  <strong>Entered:</strong>
  <%= @student.entered %>
</p>
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>